# Generated by Django 5.1.4 on 2025-02-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
